services:
  backend:
    build: ./backend
    container_name: ecommerce_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  admin:
    build: ./admin
    container_name: ecommerce_admin
    ports:
      - "3002:3001"
    env_file:
      - ./admin/.env
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  nginx:
    build: ./nginx
    container_name: ecommerce_nginx
    ports:
      - "80:80"
    depends_on:
     - frontend
     - backend
    restart: always

volumes:
  mongo_data:
